name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to increment (major/minor/patch)'
        default: 'patch'
        required: true

jobs:
  create-tag:
    name: Creating ${{ github.event.inputs.version }} release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Creating new tag
      run: |
        echo "Hello version ${{ github.event.inputs.version }}"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action and ${{ github.actor }}"
        ./do tag "${{github.event.inputs.version}}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
