name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to increment (major/minor/patch)'
        default: 'patch'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Creating new tag
      run: |
        echo "Hello version ${{ github.event.inputs.version }}"
        ./do tag "${{github.event.inputs.version}}"
